### ISSUE TITLE
Explaination of Config File keypoint_rcnn_fbnetv3a_dsmask_C4.yaml

### ISSUE THREAD

**Issue by ashutoshsoni891** [facebookresearch/d2go#104]
Hi there!

I am training custom kepoint detection model with 60 points on d2go . I am looking for some explaination / documentation regarding CONFIG file parameters .

**Comment by wat3rBro** [comment]
@ashutoshsoni891 Hi, are you looking for documentation about how to register dataset with 60 keypoints? Detectron2's tutorial can be useful: https://detectron2.readthedocs.io/en/v0.2/tutorials/datasets.html.

**Comment by ashutoshsoni891** [comment]
Hi @wat3rBro , I am looking for explaination of CONFIG VARIABLES that are present in config file. 
For example 

```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  KEYPOINT_ON: True
  MASK_ON: False
  # WEIGHTS: manifold://xiaoliangdai_model/tree/xiaoliangdai/20210126/faster_rcnn.ULfbyCBZtx/e2e_train/model_0179999.pth
  FBNET_V2:
    ARCH: "FBNetV3_A_dsmask"
    NORM: "naiveSyncBN"
    WIDTH_DIVISOR: 8
    SCALE_FACTOR: 0.75
  BACKBONE:
    NAME: FBNetV2C4Backbone
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]  # NOTE: for smaller resolution (320 < 512)
    # SIZES: [[32, 64, 96, 128, 160]]  # NOTE: for smaller resolution (320 < 512)
  RPN:
    HEAD_NAME: FBNetV2RpnHead
    IN_FEATURES: ["trunk3"]
    # Default values are 12000/2000 for train and 6000/1000 for test. In FBNet
    # we use smaller numbers.  TODO: reduce proposals for test in .yaml directly.
    POST_NMS_TOPK_TEST: 30
    POST_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 4000
  ROI_HEADS:
    NUM_CLASSES: 1
    IN_FEATURES: ["trunk3"]
    NAME: StandardROIHeads
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5  # 1.0? Keypoint AP degrades (though box AP improves) when using plain L1 loss
    NAME: FBNetV2RoIBoxHead
    POOLER_RESOLUTION: 6
    NORM: "naiveSyncBN"
  ROI_MASK_HEAD:
    NAME: "FBNetV2RoIMaskHead"
    NUM_CONV: 0
    POOLER_RESOLUTION: 6
  ROI_KEYPOINT_HEAD:
    NAME: FBNetV2RoIKeypointHeadKPRCNNIRFPredictorNoUpscale
    POOLER_RESOLUTION: 6
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    # NUM_KEYPOINTS: 100
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
MODEL_EMA:
  ENABLED: True
  DECAY: 0.9998
```
