### ISSUE TITLE
The performance of the original deformable DETR is not replicable

### ISSUE THREAD

**Issue by kibok90** [facebookresearch/d2go#61]
Hi,

I want to check if this implementation can replicate the performance of the original deformable DETR (with ResNet-50 on COCO), but I couldn't match the performance.

replication w/ [[the original code](https://github.com/fundamentalvision/Deformable-DETR)]:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.437
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.627
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.475

replication w/ this repo (using the configs below):
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.413
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.599
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.450

Could you confirm if your code can replicate the original deformable DETR performance?
It would be great if you provide a fix on my configs below, or just your configs to replicate it.

---

Here are the configs I added/modified in [[the fbnet config file](https://github.com/facebookresearch/d2go/blob/master/projects_oss/detr/configs/deformable_detr_fbnetv3a_bs16.yaml)] to get the performances above:
```
MODEL:
  WEIGHTS: "R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE: [False, False, False, False]
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES: ['res3', 'res4', 'res5']
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    WIDTH_PER_GROUP: 64
  DETR:
    NUM_FEATURE_LEVELS: 4
SOLVER:
  STEPS: (295680,)
  MAX_ITER: 369600
```
The resnet configs are mostly from [[the default detectron2 config](https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L467-L499)].
I used 8 gpus to train this model, which takes ~2 days for training.
